//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class optbazaEntities : DbContext
    {
        private static optbazaEntities _context;
        public optbazaEntities()
            : base("name=optbazaEntities")
        {
        }
        public static optbazaEntities GetContext()
        {
            if (_context == null)
                _context = new optbazaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<postavshiki> postavshiki { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tovar> tovar { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
